version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./compose/tests/Dockerfile
    image: faketwitter_tests
    stdin_open: true
    tty: true
    volumes:
      - ./tests:/tests
    #command: python fakeTwitter_tests.py