# Generated by Django 3.1.7 on 2021-04-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_messages', '0002_auto_20210414_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twitter_messages.message'),
        ),
    ]
